# Practical 09
### Aim
Demonstrate the Data science life cycle and perform Univariate , bivariate and multivariate analysis on a real-world dataset

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("employee.csv")

### 1.Univariate

In [12]:
df["Age"].describe()

count    1470.000000
mean       36.923810
std         9.135373
min        18.000000
25%        30.000000
50%        36.000000
75%        43.000000
max        60.000000
Name: Age, dtype: float64

### 2.Bivariate

In [13]:
df[["DistanceFromHome","Education"]].describe()

       DistanceFromHome    Education
count       1470.000000  1470.000000
mean           9.192517     2.912925
std            8.106864     1.024165
min            1.000000     1.000000
25%            2.000000     2.000000
50%            7.000000     3.000000
75%           14.000000     4.000000
max           29.000000     5.000000

### 3.Multivariate

In [14]:
df[["EmployeeNumber","TotalWorkingYears","TrainingTimesLastYear"]].describe()

       EmployeeNumber  TotalWorkingYears  TrainingTimesLastYear
count     1470.000000        1470.000000            1470.000000
mean      1024.865306          11.279592               2.799320
std        602.024335           7.780782               1.289271
min          1.000000           0.000000               0.000000
25%        491.250000           6.000000               2.000000
50%       1020.500000          10.000000               3.000000
75%       1555.750000          15.000000               3.000000
max       2068.000000          40.000000               6.000000